import { Building, Skin } from './types';

export const INITIAL_ENERGY = 50;
export const MAX_ENERGY = 50;
export const ENERGY_REFILL_RATE_MS = 60 * 60 * 1000; // 1 energy per hour (slow for demo, maybe faster?)
export const ENERGY_REFILL_AMOUNT = 1;

export const BUILDING_TYPES = {
  bank: {
    name: 'Royal Bank',
    basePrice: 50000,
    baseIncome: 1200,
    icon: 'landmark',
  },
  hotel: {
    name: 'Gold Plaza',
    basePrice: 100000,
    baseIncome: 2500,
    icon: 'hotel',
  },
  shop: {
    name: 'Emerald Mart',
    basePrice: 25000,
    baseIncome: 600,
    icon: 'shopping-bag',
  },
  penthouse: {
    name: 'The Penthouse',
    basePrice: 200000,
    baseIncome: 5000,
    icon: 'home',
  },
  casino: {
    name: 'Vegas King',
    basePrice: 150000,
    baseIncome: 3500,
    icon: 'clover',
  },
};

export const GRID_SIZE = 4; // 4x4 grid
export const TOTAL_TILES = GRID_SIZE * GRID_SIZE;

export enum TileType {
  GO = 'go',
  PROPERTY = 'property',
  RAID = 'raid',
  CHANCE = 'chance',
  TAX = 'tax',
}

export const BOARD_TILES: TileType[] = [
  TileType.GO, TileType.PROPERTY, TileType.PROPERTY, TileType.RAID,
  TileType.PROPERTY, TileType.CHANCE, TileType.PROPERTY, TileType.PROPERTY,
  TileType.RAID, TileType.PROPERTY, TileType.PROPERTY, TileType.CHANCE,
  TileType.PROPERTY, TileType.TAX, TileType.PROPERTY, TileType.PROPERTY,
];

export const getUpgradeCost = (basePrice: number, level: number) => {
  return Math.floor(basePrice * Math.pow(1.5, level));
};

export const SKINS: Skin[] = [
  { id: 'king', name: 'Capital King', emoji: '👑', description: 'The ultimate tycoon.', price: 1000000, level: 1 },
  { id: 'sleepy_dog', name: 'Sleepy Doggy', emoji: '🐶', description: 'Napping on a pile of coins.', price: 5000, level: 1 },
  { id: 'cozy_cat', name: 'Cozy Kitty', emoji: '🐱', description: 'Purring in a velvet basket.', price: 5500, level: 1 },
  { id: 'fluffy_mouse', name: 'Fluffy Mouse', emoji: '🐭', description: 'Tiny ears, big dreams.', price: 4000, level: 1 },
  { id: 'snug_hamster', name: 'Snug Hamster', emoji: '🐹', description: 'Stuffed with seeds and gold.', price: 4200, level: 1 },
  { id: 'warm_rabbit', name: 'Warm Bunny', emoji: '🐰', description: 'Hops into a soft blanket.', price: 6000, level: 1 },
  { id: 'soft_fox', name: 'Soft Fox', emoji: '🦊', description: 'Cunningly comfortable.', price: 7000, level: 1 },
  { id: 'dreamy_bear', name: 'Dreamy Bear', emoji: '🐻', description: 'Hibernating with honey.', price: 8000, level: 1 },
  { id: 'plush_panda', name: 'Plush Panda', emoji: '🐼', description: 'Bamboo and silk pillows.', price: 8500, level: 1 },
  { id: 'gentle_koala', name: 'Gentle Koala', emoji: '🐨', description: 'Eucalyptus scented dreams.', price: 7500, level: 1 },
  { id: 'calm_tiger', name: 'Calm Tiger', emoji: '🐯', description: 'A fierce nap.', price: 12000, level: 1 },
  { id: 'quiet_lion', name: 'Quiet Lion', emoji: '🦁', description: 'King of the couch.', price: 15000, level: 1 },
  { id: 'peaceful_cow', name: 'Peaceful Cow', emoji: '🐮', description: 'Grazing on green cash.', price: 9000, level: 1 },
  { id: 'lazy_pig', name: 'Lazy Piggy', emoji: '🐷', description: 'Rolling in luxury mud.', price: 6500, level: 1 },
  { id: 'relaxed_frog', name: 'Relaxed Frog', emoji: '🐸', description: 'Lily pad lounging.', price: 5800, level: 1 },
  { id: 'comfy_monkey', name: 'Comfy Monkey', emoji: '🐵', description: 'Swinging in a hammock.', price: 7200, level: 1 },
  { id: 'snug_penguin', name: 'Snug Penguin', emoji: '🐧', description: 'Ice-cold cool, warm heart.', price: 8800, level: 1 },
  { id: 'soft_bird', name: 'Soft Birdie', emoji: '🐦', description: 'Nesting in gold silk.', price: 4500, level: 1 },
  { id: 'warm_chick', name: 'Warm Chick', emoji: '🐤', description: 'Freshly hatched fortune.', price: 3500, level: 1 },
  { id: 'fluffy_duck', name: 'Fluffy Duck', emoji: '🦆', description: 'Quacking for comfort.', price: 5200, level: 1 },
  { id: 'dreamy_owl', name: 'Dreamy Owl', emoji: '🦉', description: 'Wise and well-rested.', price: 9500, level: 1 },
  { id: 'soft_bat', name: 'Soft Bat', emoji: '🦇', description: 'Hanging out in style.', price: 6800, level: 1 },
  { id: 'warm_wolf', name: 'Warm Wolf', emoji: '🐺', description: 'Howling at the moon-rug.', price: 11000, level: 1 },
  { id: 'cozy_boar', name: 'Cozy Boar', emoji: '🐗', description: 'Wildly comfortable.', price: 7800, level: 1 },
  { id: 'plush_horse', name: 'Plush Horse', emoji: '🐴', description: 'Galloping to the spa.', price: 13000, level: 1 },
  { id: 'dreamy_unicorn', name: 'Dreamy Unicorn', emoji: '🦄', description: 'Magic and marshmallows.', price: 50000, level: 1 },
  { id: 'soft_bee', name: 'Soft Bee', emoji: '🐝', description: 'Busy being cozy.', price: 4800, level: 1 },
  { id: 'warm_snail', name: 'Warm Snail', emoji: '🐌', description: 'Home is where the shell is.', price: 3000, level: 1 },
  { id: 'cozy_ladybug', name: 'Cozy Ladybug', emoji: '🐞', description: 'Lucky and lazy.', price: 3200, level: 1 },
  { id: 'soft_butterfly', name: 'Soft Butterfly', emoji: '🦋', description: 'Fluttering in silk.', price: 5400, level: 1 },
  { id: 'warm_turtle', name: 'Warm Turtle', emoji: '🐢', description: 'Slow and steady comfort.', price: 6200, level: 1 },
  { id: 'cozy_snake', name: 'Cozy Snake', emoji: '🐍', description: 'Slithering into a sweater.', price: 5600, level: 1 },
  { id: 'soft_lizard', name: 'Soft Lizard', emoji: '🦎', description: 'Basking in the glow.', price: 4400, level: 1 },
  { id: 'warm_octopus', name: 'Warm Octopus', emoji: '🐙', description: 'Eight arms for hugging.', price: 9200, level: 1 },
  { id: 'cozy_squid', name: 'Cozy Squid', emoji: '🦑', description: 'Inking in comfort.', price: 8600, level: 1 },
  { id: 'soft_shrimp', name: 'Soft Shrimp', emoji: '🦐', description: 'Curled up tight.', price: 3800, level: 1 },
  { id: 'warm_crab', name: 'Warm Crab', emoji: '🦀', description: 'Pinching the pillows.', price: 6400, level: 1 },
  { id: 'cozy_fish', name: 'Cozy Fish', emoji: '🐠', description: 'Swimming in silk.', price: 4600, level: 1 },
  { id: 'soft_whale', name: 'Soft Whale', emoji: '🐋', description: 'A giant nap.', price: 20000, level: 1 },
  { id: 'warm_shark', name: 'Warm Shark', emoji: '🦈', description: 'Sharp teeth, soft heart.', price: 18000, level: 1 },
  { id: 'cozy_crocodile', name: 'Cocooning Croc', emoji: '🐊', description: 'Snapping up snacks.', price: 14000, level: 50 },
  { id: 'soft_leopard', name: 'Cocooning Leopard', emoji: '🐆', description: 'Spotted in the spa.', price: 16000, level: 50 },
  { id: 'warm_zebra', name: 'Cocooning Zebra', emoji: '🦓', description: 'Stripes of silk.', price: 12500, level: 50 },
  { id: 'cozy_gorilla', name: 'Cocooning Gorilla', emoji: '🦍', description: 'Strong and snuggly.', price: 17500, level: 50 },
  { id: 'soft_elephant', name: 'Cocooning Elephant', emoji: '🐘', description: 'Trunk full of toys.', price: 19000, level: 50 },
  { id: 'warm_rhino', name: 'Cocooning Rhino', emoji: '🦏', description: 'Tough skin, soft bed.', price: 15500, level: 50 },
  { id: 'cozy_camel', name: 'Cocooning Camel', emoji: '🐪', description: 'Humps of happiness.', price: 11500, level: 50 },
  { id: 'soft_giraffe', name: 'Cocooning Giraffe', emoji: '🦒', description: 'High-level comfort.', price: 14500, level: 50 },
  { id: 'warm_kangaroo', name: 'Cocooning Kangaroo', emoji: '🦘', description: 'Pouch of peace.', price: 13500, level: 50 },
  { id: 'cozy_sheep', name: 'Cocooning Sheep', emoji: '🐑', description: 'Counting yourself to sleep.', price: 10500, level: 50 },
  { id: 'soft_llama', name: 'Cocooning Llama', emoji: '🦙', description: 'No drama, just llama.', price: 11000, level: 50 },
  { id: 'warm_goat', name: 'Cocooning Goat', emoji: '🐐', description: 'Greatest of all time naps.', price: 9800, level: 50 },
  { id: 'cozy_deer', name: 'Cocooning Deer', emoji: '🦌', description: 'Prancing in pajamas.', price: 12800, level: 50 },
  { id: 'soft_poodle', name: 'Cocooning Poodle', emoji: '🐩', description: 'Fancy and fluffy.', price: 14000, level: 50 },
  { id: 'warm_rooster', name: 'Cocooning Rooster', emoji: '🐓', description: 'Waking up slowly.', price: 8200, level: 50 },
  { id: 'cozy_turkey', name: 'Cocooning Turkey', emoji: '🦃', description: 'Gobbling up gold.', price: 9400, level: 50 },
  { id: 'soft_peacock', name: 'Cocooning Peacock', emoji: '🦚', description: 'Showing off the silk.', price: 16500, level: 50 },
  { id: 'warm_swan', name: 'Cocooning Swan', emoji: '🦢', description: 'Graceful and gentle.', price: 15000, level: 50 },
  { id: 'cozy_raccoon', name: 'Cocooning Raccoon', emoji: '🦝', description: 'Trash to treasure naps.', price: 10200, level: 50 },
  { id: 'soft_skunk', name: 'Cocooning Skunk', emoji: '🦨', description: 'Smelling like lavender.', price: 9600, level: 50 },
  { id: 'warm_badger', name: 'Cocooning Badger', emoji: '🦡', description: 'Digging for dreams.', price: 10800, level: 50 },
  { id: 'cozy_otter', name: 'Cocooning Otter', emoji: '🦦', description: 'Holding hands in sleep.', price: 11200, level: 50 },
  { id: 'soft_sloth', name: 'Cocooning Sloth', emoji: '🦥', description: 'The master of cocooning.', price: 25000, level: 50 },
  { id: 'warm_hedgehog', name: 'Cocooning Hedgehog', emoji: '🦔', description: 'Prickly but peaceful.', price: 8400, level: 50 },
  { id: 'cozy_squirrel', name: 'Cocooning Squirrel', emoji: '🐿️', description: 'Nuts for naps.', price: 7600, level: 50 },
  { id: 'soft_mouse_2', name: 'Cocooning Velvet Mouse', emoji: '🐁', description: 'White as a cloud.', price: 4100, level: 50 },
  { id: 'warm_rat', name: 'Cocooning Rat', emoji: '🐀', description: 'Smart and snug.', price: 3900, level: 50 },
  { id: 'cozy_dove', name: 'Cocooning Dove', emoji: '🕊️', description: 'Peace and pillows.', price: 12200, level: 50 },
  { id: 'soft_eagle', name: 'Cocooning Eagle', emoji: '🦅', description: 'Soaring in dreams.', price: 15500, level: 50 },
  { id: 'warm_parrot', name: 'Cocooning Parrot', emoji: '🦜', description: 'Repeating "cozy".', price: 13200, level: 50 },
  { id: 'cozy_dino', name: 'Cocooning Dino', emoji: '🦖', description: 'Ancient comfort.', price: 22000, level: 50 },
  { id: 'soft_dino_2', name: 'Cocooning Soft Dino', emoji: '🦕', description: 'Long neck, long nap.', price: 21000, level: 50 },
  { id: 'warm_bug', name: 'Cocooning Bug', emoji: '🐛', description: 'Caterpillar cocoon.', price: 3100, level: 50 },
  { id: 'cozy_ant', name: 'Cocooning Ant', emoji: '🐜', description: 'Tiny but tired.', price: 2800, level: 50 },
  { id: 'soft_spider', name: 'Cocooning Spider', emoji: '🕷️', description: 'Spinning silk beds.', price: 4300, level: 50 },
  { id: 'warm_scorpion', name: 'Cocooning Scorpion', emoji: '🦂', description: 'Stinging for sleep.', price: 5300, level: 50 },
  { id: 'cozy_blowfish', name: 'Cocooning Blowfish', emoji: '🐡', description: 'Puffing up for peace.', price: 6300, level: 50 },
  { id: 'soft_dolphin', name: 'Cocooning Dolphin', emoji: '🐬', description: 'Splashing in silk.', price: 14200, level: 50 },
  { id: 'warm_whale_2', name: 'Cocooning Whale', emoji: '🐳', description: 'Blowing bubbles of bliss.', price: 19500, level: 50 },
  { id: 'cozy_leopard_2', name: 'Cocooning Leopard', emoji: '🐆', description: 'Fast asleep.', price: 16200, level: 50 },
  { id: 'soft_ram', name: 'Cocooning Ram', emoji: '🐏', description: 'Wooly and wealthy.', price: 10600, level: 50 },
  { id: 'warm_ewe', name: 'Cocooning Ewe', emoji: '🐑', description: 'Sheepish success.', price: 10400, level: 50 },
  { id: 'cozy_ox', name: 'Cocooning Ox', emoji: '🐂', description: 'Strong and still.', price: 11600, level: 50 },
  { id: 'soft_water_buffalo', name: 'Cocooning Buffalo', emoji: '🐃', description: 'Wildly relaxed.', price: 11800, level: 50 },
  { id: 'warm_hippo', name: 'Cocooning Hippo', emoji: '🦛', description: 'Heavy sleeper.', price: 17200, level: 50 },
  { id: 'cozy_llama_2', name: 'Cocooning Llama', emoji: '🦙', description: 'Fluffy and fun.', price: 11400, level: 50 },
  { id: 'soft_camel_2', name: 'Cocooning Camel', emoji: '🐫', description: 'Two humps of comfort.', price: 11700, level: 50 },
  { id: 'warm_donkey', name: 'Cocooning Donkey', emoji: '🫏', description: 'Stubbornly snug.', price: 8500, level: 50 },
  { id: 'cozy_mule', name: 'Cocooning Mule', emoji: '🐎', description: 'Hardworking napper.', price: 12600, level: 50 },
  { id: 'soft_cat_face', name: 'Cocooning Kitty Face', emoji: '🐱', description: 'Just the whiskers.', price: 5100, level: 50 },
  { id: 'warm_dog_face', name: 'Cocooning Puppy Face', emoji: '🐶', description: 'Puppy eyes.', price: 5200, level: 50 },
  { id: 'cozy_mouse_face', name: 'Cocooning Mouse Face', emoji: '🐭', description: 'Squeaky clean.', price: 4100, level: 50 },
  { id: 'soft_hamster_face', name: 'Cocooning Hamster Face', emoji: '🐹', description: 'Chubby cheeks.', price: 4300, level: 50 },
  { id: 'warm_rabbit_face', name: 'Cocooning Bunny Face', emoji: '🐰', description: 'Twitchy nose.', price: 6100, level: 50 },
  { id: 'cozy_fox_face', name: 'Cocooning Fox Face', emoji: '🦊', description: 'Foxy dreams.', price: 7100, level: 50 },
  { id: 'soft_bear_face', name: 'Cocooning Bear Face', emoji: '🐻', description: 'Bear hugs.', price: 8100, level: 50 },
  { id: 'warm_panda_face', name: 'Cocooning Panda Face', emoji: '🐼', description: 'Panda eyes.', price: 8600, level: 50 },
  { id: 'cozy_koala_face', name: 'Cocooning Koala Face', emoji: '🐨', description: 'Koala-ty time.', price: 7600, level: 50 },
  { id: 'soft_tiger_face', name: 'Cocooning Tiger Face', emoji: '🐯', description: 'Striped sleep.', price: 12100, level: 50 },
  { id: 'warm_lion_face', name: 'Cocooning Lion Face', emoji: '🦁', description: 'Mane event.', price: 15100, level: 50 },
  { id: 'cozy_cow_face', name: 'Cocooning Cow Face', emoji: '🐮', description: 'Moo-dy morning.', price: 9100, level: 50 },
  { id: 'soft_pig_face', name: 'Cocooning Pig Face', emoji: '🐷', description: 'Oink of peace.', price: 6600, level: 50 },
  { id: 'warm_frog_face', name: 'Cocooning Frog Face', emoji: '🐸', description: 'Ribbit of rest.', price: 5900, level: 50 },
  { id: 'cozy_monkey_face', name: 'Cocooning Monkey Face', emoji: '🐵', description: 'Monkeying around.', price: 7300, level: 50 },
  { id: 'soft_chicken', name: 'Cocooning Chicken', emoji: '🐔', description: 'Clucking comfort.', price: 8300, level: 50 },
  { id: 'warm_penguin_face', name: 'Cocooning Penguin Face', emoji: '🐧', description: 'Waddling to bed.', price: 8900, level: 50 },
  { id: 'cozy_bird_face', name: 'Cocooning Bird Face', emoji: '🐦', description: 'Chirping dreams.', price: 4600, level: 50 },
  { id: 'soft_duck_face', name: 'Cocooning Duck Face', emoji: '🦆', description: 'Ducky dreams.', price: 5300, level: 50 },
  { id: 'warm_owl_face', name: 'Cocooning Owl Face', emoji: '🦉', description: 'Hoot of happiness.', price: 9600, level: 50 },
  { id: 'cozy_bat_face', name: 'Cocooning Bat Face', emoji: '🦇', description: 'Batty for bed.', price: 6900, level: 50 },
  { id: 'soft_wolf_face', name: 'Cocooning Wolf Face', emoji: '🐺', description: 'Wolfish nap.', price: 11100, level: 50 },
  { id: 'warm_boar_face', name: 'Cocooning Boar Face', emoji: '🐗', description: 'Boar-ing sleep.', price: 7900, level: 50 },
  { id: 'cozy_horse_face', name: 'Cocooning Horse Face', emoji: '🐴', description: 'Neigh-borhood nap.', price: 13100, level: 50 },
  { id: 'soft_unicorn_face', name: 'Cocooning Unicorn Face', emoji: '🦄', description: 'Unicorn magic.', price: 51000, level: 50 },
  { id: 'warm_bee_face', name: 'Cocooning Bee Face', emoji: '🐝', description: 'Buzzing bliss.', price: 4900, level: 50 },
  { id: 'cozy_ladybug_face', name: 'Cocooning Ladybug Face', emoji: '🐞', description: 'Ladybug luck.', price: 3300, level: 50 },
  { id: 'soft_butterfly_face', name: 'Cocooning Butterfly Face', emoji: '🦋', description: 'Butterfly bliss.', price: 5500, level: 50 },
  { id: 'warm_turtle_face', name: 'Cocooning Turtle Face', emoji: '🐢', description: 'Turtle time.', price: 6300, level: 50 },
  { id: 'cozy_snake_face', name: 'Cocooning Snake Face', emoji: '🐍', description: 'Snake snuggle.', price: 5700, level: 50 },
  { id: 'soft_lizard_face', name: 'Cocooning Lizard Face', emoji: '🦎', description: 'Lizard lounge.', price: 4500, level: 50 },
  { id: 'warm_octopus_face', name: 'Cocooning Octopus Face', emoji: '🐙', description: 'Octo-nap.', price: 9300, level: 50 },
  { id: 'cozy_squid_face', name: 'Cocooning Squid Face', emoji: '🦑', description: 'Squid snug.', price: 8700, level: 50 },
  { id: 'soft_shrimp_face', name: 'Cocooning Shrimp Face', emoji: '🦐', description: 'Shrimp sleep.', price: 3900, level: 50 },
  { id: 'warm_crab_face', name: 'Cocooning Crab Face', emoji: '🦀', description: 'Crabby comfort.', price: 6500, level: 50 },
  { id: 'cozy_fish_face', name: 'Cocooning Fish Face', emoji: '🐠', description: 'Fishy fortune.', price: 4700, level: 50 },
  { id: 'soft_whale_face', name: 'Cocooning Whale Face', emoji: '🐋', description: 'Whale of a time.', price: 20100, level: 50 },
  { id: 'warm_shark_face', name: 'Cocooning Shark Face', emoji: '🦈', description: 'Sharky sleep.', price: 18100, level: 50 },
  { id: 'cozy_crocodile_face', name: 'Cocooning Croc Face', emoji: '🐊', description: 'Croc comfort.', price: 14100, level: 50 },
  { id: 'soft_leopard_face', name: 'Cocooning Leopard Face', emoji: '🐆', description: 'Leopard lounge.', price: 16100, level: 50 },
  { id: 'warm_zebra_face', name: 'Cocooning Zebra Face', emoji: '🦓', description: 'Zebra zest.', price: 12600, level: 50 },
  { id: 'cozy_gorilla_face', name: 'Cocooning Gorilla Face', emoji: '🦍', description: 'Gorilla glow.', price: 17600, level: 50 },
  { id: 'soft_elephant_face', name: 'Cocooning Elephant Face', emoji: '🐘', description: 'Elephant ease.', price: 19100, level: 50 },
  { id: 'warm_rhino_face', name: 'Cocooning Rhino Face', emoji: '🦏', description: 'Rhino rest.', price: 15600, level: 50 },
  { id: 'cozy_camel_face', name: 'Cocooning Camel Face', emoji: '🐪', description: 'Camel calm.', price: 11600, level: 50 },
  { id: 'soft_giraffe_face', name: 'Cocooning Giraffe Face', emoji: '🦒', description: 'Giraffe gentle.', price: 14600, level: 50 },
  { id: 'warm_kangaroo_face', name: 'Cocooning Kangaroo Face', emoji: '🦘', description: 'Kangaroo kickback.', price: 13600, level: 50 },
  { id: 'cozy_sheep_face', name: 'Cocooning Sheep Face', emoji: '🐑', description: 'Sheepish sleep.', price: 10600, level: 50 },
  { id: 'soft_llama_face', name: 'Cocooning Llama Face', emoji: '🦙', description: 'Llama love.', price: 11100, level: 50 },
  { id: 'warm_goat_face', name: 'Cocooning Goat Face', emoji: '🐐', description: 'Goat glow.', price: 9900, level: 50 },
  { id: 'cozy_deer_face', name: 'Cocooning Deer Face', emoji: '🦌', description: 'Deer dreams.', price: 12900, level: 50 },
  { id: 'soft_poodle_face', name: 'Cocooning Poodle Face', emoji: '🐩', description: 'Poodle peace.', price: 14100, level: 50 },
  { id: 'warm_rooster_face', name: 'Cocooning Rooster Face', emoji: '🐓', description: 'Rooster rest.', price: 8300, level: 50 },
  { id: 'cozy_turkey_face', name: 'Cocooning Turkey Face', emoji: '🦃', description: 'Turkey time.', price: 9500, level: 50 },
  { id: 'soft_peacock_face', name: 'Cocooning Peacock Face', emoji: '🦚', description: 'Peacock peace.', price: 16600, level: 50 },
  { id: 'warm_swan_face', name: 'Cocooning Swan Face', emoji: '🦢', description: 'Swan soft.', price: 15100, level: 50 },
  { id: 'cozy_raccoon_face', name: 'Cocooning Raccoon Face', emoji: '🦝', description: 'Raccoon rest.', price: 10300, level: 50 },
  { id: 'soft_skunk_face', name: 'Cocooning Skunk Face', emoji: '🦨', description: 'Skunk snug.', price: 9700, level: 50 },
  { id: 'warm_badger_face', name: 'Cocooning Badger Face', emoji: '🦡', description: 'Badger bliss.', price: 10900, level: 50 },
  { id: 'cozy_otter_face', name: 'Cocooning Otter Face', emoji: '🦦', description: 'Otter ease.', price: 11300, level: 50 },
  { id: 'soft_sloth_face', name: 'Cocooning Sloth Face', emoji: '🦥', description: 'Sloth slow.', price: 25100, level: 50 },
  { id: 'warm_hedgehog_face', name: 'Cocooning Hedgehog Face', emoji: '🦔', description: 'Hedgehog hug.', price: 8500, level: 50 },
  { id: 'cozy_squirrel_face', name: 'Cocooning Squirrel Face', emoji: '🐿️', description: 'Squirrel snug.', price: 7700, level: 50 },
  { id: 'soft_mouse_face_2', name: 'Cocooning Velvet Mouse Face', emoji: '🐁', description: 'Mouse magic.', price: 4200, level: 50 },
  { id: 'warm_rat_face', name: 'Cocooning Rat Face', emoji: '🐀', description: 'Rat rest.', price: 4000, level: 50 },
  { id: 'cozy_dove_face', name: 'Cocooning Dove Face', emoji: '🕊️', description: 'Dove dreams.', price: 12300, level: 50 },
  { id: 'soft_eagle_face', name: 'Cocooning Eagle Face', emoji: '🦅', description: 'Eagle ease.', price: 15600, level: 50 },
  { id: 'warm_parrot_face', name: 'Cocooning Parrot Face', emoji: '🦜', description: 'Parrot peace.', price: 13300, level: 50 },
  { id: 'cozy_dino_face', name: 'Cocooning Dino Face', emoji: '🦖', description: 'Dino dreams.', price: 22100, level: 50 },
  { id: 'soft_dino_face_2', name: 'Cocooning Dino Face', emoji: '🦕', description: 'Dino ease.', price: 21100, level: 50 },
  { id: 'warm_bug_face', name: 'Cocooning Bug Face', emoji: '🐛', description: 'Bug bliss.', price: 3200, level: 50 },
  { id: 'cozy_ant_face', name: 'Cocooning Ant Face', emoji: '🐜', description: 'Ant ease.', price: 2900, level: 50 },
  { id: 'soft_spider_face', name: 'Cocooning Spider Face', emoji: '🕷️', description: 'Spider snug.', price: 4400, level: 50 },
  { id: 'warm_scorpion_face', name: 'Cocooning Scorpion Face', emoji: '🦂', description: 'Scorpion sleep.', price: 5400, level: 50 },
  { id: 'cozy_blowfish_face', name: 'Cocooning Blowfish Face', emoji: '🐡', description: 'Blowfish bliss.', price: 6400, level: 50 },
  { id: 'soft_dolphin_face', name: 'Cocooning Dolphin Face', emoji: '🐬', description: 'Dolphin dreams.', price: 14300, level: 50 },
  { id: 'warm_whale_face_2', name: 'Cocooning Whale Face', emoji: '🐳', description: 'Whale bliss.', price: 19600, level: 50 },
  { id: 'cozy_leopard_face_2', name: 'Cocooning Leopard Face', emoji: '🐆', description: 'Leopard lounge.', price: 16300, level: 50 },
  { id: 'soft_ram_face', name: 'Cocooning Ram Face', emoji: '🐏', description: 'Ram rest.', price: 10700, level: 50 },
  { id: 'warm_ewe_face', name: 'Cocooning Ewe Face', emoji: '🐑', description: 'Ewe ease.', price: 10500, level: 50 },
  { id: 'cozy_ox_face', name: 'Cocooning Ox Face', emoji: '🐂', description: 'Ox ease.', price: 11700, level: 50 },
  { id: 'soft_water_buffalo_face', name: 'Cocooning Buffalo Face', emoji: '🐃', description: 'Buffalo bliss.', price: 11900, level: 50 },
  { id: 'warm_hippo_face', name: 'Cocooning Hippo Face', emoji: '🦛', description: 'Hippo hug.', price: 17300, level: 50 },
  { id: 'cozy_llama_face_2', name: 'Cocooning Llama Face', emoji: '🦙', description: 'Llama lounge.', price: 11500, level: 50 },
  { id: 'soft_camel_face_2', name: 'Cocooning Camel Face', emoji: '🐫', description: 'Camel calm.', price: 11800, level: 50 },
  { id: 'warm_donkey_face', name: 'Cocooning Donkey Face', emoji: '🫏', description: 'Donkey dreams.', price: 8600, level: 50 },
  { id: 'cozy_mule_face', name: 'Cocooning Mule Face', emoji: '🐎', description: 'Mule magic.', price: 12700, level: 50 },
  { id: 'soft_cat_face_2', name: 'Cocooning Cat Face', emoji: '🐱', description: 'Cat calm.', price: 5200, level: 50 },
  { id: 'warm_dog_face_2', name: 'Cocooning Dog Face', emoji: '🐶', description: 'Dog dreams.', price: 5300, level: 50 },
  { id: 'cozy_mouse_face_2', name: 'Cocooning Mouse Face', emoji: '🐭', description: 'Mouse magic.', price: 4200, level: 50 },
  { id: 'soft_hamster_face_2', name: 'Cocooning Hamster Face', emoji: '🐹', description: 'Hamster hug.', price: 4400, level: 50 },
  { id: 'warm_rabbit_face_2', name: 'Cocooning Rabbit Face', emoji: '🐰', description: 'Rabbit rest.', price: 6200, level: 50 },
  { id: 'cozy_fox_face_2', name: 'Cocooning Fox Face', emoji: '🦊', description: 'Fox fortune.', price: 7200, level: 50 },
  { id: 'soft_bear_face_2', name: 'Cocooning Bear Face', emoji: '🐻', description: 'Bear bliss.', price: 8200, level: 50 },
  { id: 'warm_panda_face_2', name: 'Cocooning Panda Face', emoji: '🐼', description: 'Panda peace.', price: 8700, level: 50 },
  { id: 'cozy_koala_face_2', name: 'Cocooning Koala Face', emoji: '🐨', description: 'Koala calm.', price: 7700, level: 50 },
  { id: 'soft_tiger_face_2', name: 'Cocooning Tiger Face', emoji: '🐯', description: 'Tiger time.', price: 12200, level: 50 },
  { id: 'warm_lion_face_2', name: 'Cocooning Lion Face', emoji: '🦁', description: 'Lion lounge.', price: 15200, level: 50 },
  { id: 'cozy_cow_face_2', name: 'Cocooning Cow Face', emoji: '🐮', description: 'Cow calm.', price: 9200, level: 50 },
  { id: 'soft_pig_face_2', name: 'Cocooning Pig Face', emoji: '🐷', description: 'Piggy peace.', price: 6700, level: 50 },
  { id: 'warm_frog_face_2', name: 'Cocooning Frog Face', emoji: '🐸', description: 'Froggy fortune.', price: 6000, level: 50 },
  { id: 'cozy_monkey_face_2', name: 'Cocooning Monkey Face', emoji: '🐵', description: 'Monkey magic.', price: 7400, level: 50 },
  { id: 'soft_chicken_face', name: 'Cocooning Chicken Face', emoji: '🐔', description: 'Chicken calm.', price: 8400, level: 50 },
  { id: 'warm_penguin_face_2', name: 'Cocooning Penguin Face', emoji: '🐧', description: 'Penguin peace.', price: 9000, level: 50 },
  { id: 'cozy_bird_face_2', name: 'Cocooning Bird Face', emoji: '🐦', description: 'Birdie bliss.', price: 4700, level: 50 },
  { id: 'soft_duck_face_2', name: 'Cocooning Duck Face', emoji: '🦆', description: 'Ducky dreams.', price: 5400, level: 50 },
  { id: 'warm_owl_face_2', name: 'Cocooning Owl Face', emoji: '🦉', description: 'Owl ease.', price: 9700, level: 50 },
  { id: 'cozy_bat_face_2', name: 'Cocooning Bat Face', emoji: '🦇', description: 'Batty bliss.', price: 7000, level: 50 },
  { id: 'soft_wolf_face_2', name: 'Cocooning Wolf Face', emoji: '🐺', description: 'Wolfish wealth.', price: 11200, level: 50 },
  { id: 'warm_boar_face_2', name: 'Cocooning Boar Face', emoji: '🐗', description: 'Boar bliss.', price: 8000, level: 50 },
  { id: 'cozy_horse_face_2', name: 'Cocooning Horse Face', emoji: '🐴', description: 'Horse hug.', price: 13200, level: 50 },
  { id: 'soft_unicorn_face_2', name: 'Cocooning Unicorn Face', emoji: '🦄', description: 'Unicorn ease.', price: 52000, level: 50 },
  { id: 'warm_bee_face_2', name: 'Cocooning Bee Face', emoji: '🐝', description: 'Bee bliss.', price: 5000, level: 50 },
  { id: 'cozy_ladybug_face_2', name: 'Cocooning Ladybug Face', emoji: '🐞', description: 'Ladybug lounge.', price: 3400, level: 50 },
  { id: 'soft_butterfly_face_2', name: 'Cocooning Butterfly Face', emoji: '🦋', description: 'Butterfly bliss.', price: 5600, level: 50 },
  { id: 'warm_turtle_face_2', name: 'Cocooning Turtle Face', emoji: '🐢', description: 'Turtle time.', price: 6400, level: 50 },
  { id: 'cozy_snake_face_2', name: 'Cocooning Snake Face', emoji: '🐍', description: 'Snake snug.', price: 5800, level: 50 },
  { id: 'soft_lizard_face_2', name: 'Cocooning Lizard Face', emoji: '🦎', description: 'Lizard lounge.', price: 4600, level: 50 },
  { id: 'warm_octopus_face_2', name: 'Cocooning Octopus Face', emoji: '🐙', description: 'Octo-ease.', price: 9400, level: 50 },
  { id: 'cozy_squid_face_2', name: 'Cocooning Squid Face', emoji: '🦑', description: 'Squid snug.', price: 8800, level: 50 },
  { id: 'soft_shrimp_face_2', name: 'Cocooning Shrimp Face', emoji: '🦐', description: 'Shrimp sleep.', price: 4000, level: 50 },
  { id: 'warm_crab_face_2', name: 'Cocooning Crab Face', emoji: '🦀', description: 'Crabby calm.', price: 6600, level: 50 },
  { id: 'cozy_fish_face_2', name: 'Cocooning Fish Face', emoji: '🐠', description: 'Fishy fortune.', price: 4800, level: 50 },
  { id: 'soft_whale_face_2', name: 'Cocooning Whale Face', emoji: '🐋', description: 'Whale of a time.', price: 20200, level: 50 },
  { id: 'warm_shark_face_2', name: 'Cocooning Shark Face', emoji: '🦈', description: 'Sharky sleep.', price: 18200, level: 50 },
  { id: 'cozy_crocodile_face_3', name: 'Cocooning Croc Face', emoji: '🐊', description: 'Croc comfort.', price: 14200, level: 50 },
  { id: 'soft_leopard_face_3', name: 'Cocooning Leopard Face', emoji: '🐆', description: 'Leopard lounge.', price: 16200, level: 50 },
  { id: 'warm_zebra_face_2', name: 'Cocooning Zebra Face', emoji: '🦓', description: 'Zebra zest.', price: 12700, level: 50 },
  { id: 'cozy_gorilla_face_2', name: 'Cocooning Gorilla Face', emoji: '🦍', description: 'Gorilla glow.', price: 17700, level: 50 },
  { id: 'soft_elephant_face_2', name: 'Cocooning Elephant Face', emoji: '🐘', description: 'Elephant ease.', price: 19200, level: 50 },
  { id: 'warm_rhino_face_2', name: 'Cocooning Rhino Face', emoji: '🦏', description: 'Rhino rest.', price: 15700, level: 50 },
  { id: 'cozy_camel_face_3', name: 'Cocooning Camel Face', emoji: '🐪', description: 'Camel calm.', price: 11700, level: 50 },
  { id: 'soft_giraffe_face_2', name: 'Cocooning Giraffe Face', emoji: '🦒', description: 'Giraffe gentle.', price: 14700, level: 50 },
  { id: 'warm_kangaroo_face_2', name: 'Cocooning Kangaroo Face', emoji: '🦘', description: 'Kangaroo kickback.', price: 13700, level: 50 },
  { id: 'cozy_sheep_face_2', name: 'Cocooning Sheep Face', emoji: '🐑', description: 'Sheepish sleep.', price: 10700, level: 50 },
  { id: 'soft_llama_face_2', name: 'Cocooning Llama Face', emoji: '🦙', description: 'Llama love.', price: 11200, level: 50 },
  { id: 'warm_goat_face_2', name: 'Cocooning Goat Face', emoji: '🐐', description: 'Goat glow.', price: 10000, level: 50 },
  { id: 'cozy_deer_face_2', name: 'Cocooning Deer Face', emoji: '🦌', description: 'Deer dreams.', price: 13000, level: 50 },
  { id: 'soft_poodle_face_2', name: 'Cocooning Poodle Face', emoji: '🐩', description: 'Poodle peace.', price: 14200, level: 50 },
  { id: 'warm_rooster_face_2', name: 'Cocooning Rooster Face', emoji: '🐓', description: 'Rooster rest.', price: 8400, level: 50 },
  { id: 'cozy_turkey_face_2', name: 'Cocooning Turkey Face', emoji: '🦃', description: 'Turkey time.', price: 9600, level: 50 },
  { id: 'soft_peacock_face_2', name: 'Cocooning Peacock Face', emoji: '🦚', description: 'Peacock peace.', price: 16700, level: 50 },
  { id: 'warm_swan_face_2', name: 'Cocooning Swan Face', emoji: '🦢', description: 'Swan soft.', price: 15200, level: 50 },
  { id: 'cozy_raccoon_face_2', name: 'Cocooning Raccoon Face', emoji: '🦝', description: 'Raccoon rest.', price: 10400, level: 50 },
  { id: 'soft_skunk_face_2', name: 'Cocooning Skunk Face', emoji: '🦨', description: 'Skunk snug.', price: 9800, level: 50 },
  { id: 'warm_badger_face_2', name: 'Cocooning Badger Face', emoji: '🦡', description: 'Badger bliss.', price: 11000, level: 50 },
  { id: 'cozy_otter_face_2', name: 'Cocooning Otter Face', emoji: '🦦', description: 'Otter ease.', price: 11400, level: 50 },
  { id: 'soft_sloth_face_2', name: 'Cocooning Sloth Face', emoji: '🦥', description: 'Sloth slow.', price: 25200, level: 50 },
  { id: 'warm_hedgehog_face_2', name: 'Cocooning Hedgehog Face', emoji: '🦔', description: 'Hedgehog hug.', price: 8600, level: 50 },
  { id: 'cozy_squirrel_face_2', name: 'Cocooning Squirrel Face', emoji: '🐿️', description: 'Squirrel snug.', price: 7800, level: 50 },
];

export const SHOP_ITEMS = {
  energy: [
    { id: 'energy_10', amount: 10, price: 50, icon: 'zap' },
    { id: 'energy_25', amount: 25, price: 100, icon: 'zap' },
    { id: 'energy_full', amount: 50, price: 180, icon: 'zap' },
  ],
  coins: [
    { id: 'coins_small', amount: 50000, price: 100, icon: 'coins' },
    { id: 'coins_medium', amount: 250000, price: 400, icon: 'coins' },
    { id: 'coins_large', amount: 1000000, price: 1500, icon: 'coins' },
  ],
  gems: [
    { id: 'gems_small', amount: 100, price: 0.99, icon: 'diamond' },
    { id: 'gems_medium', amount: 550, price: 4.99, icon: 'diamond' },
    { id: 'gems_large', amount: 1200, price: 9.99, icon: 'diamond' },
  ]
};
